apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: thorntail-health-check
  annotations:
    iconClass: icon-jboss
    tags: thorntail, java, microservice
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    template.openshift.io/documentation-url: "https://launcher.fabric8.io/docs/thorntail-runtime.html#mission-health-check-wf-swarm"
    description: >-
      The Health Check example shows how to monitor the health of an application, which includes if an application is available and whether it is able to service requests.
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/thorntail-examples/health-check-redhat.git
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: MAVEN_MIRROR_URL
  description: URL of a Maven repository that will be used during build phase as a global Maven mirror
  displayName: Maven Mirror URL
  required: false
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: thorntail-health-check
  spec: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: runtime-thorntail-health-check
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: thorntail-health-check
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: thorntail-health-check:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-thorntail-health-check:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: thorntail-health-check
      group: io.thorntail.example
    name: thorntail-health-check
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: thorntail-health-check
      group: io.thorntail.example
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: thorntail-health-check
      group: io.thorntail.example
    name: thorntail-health-check
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: thorntail-health-check
      group: io.thorntail.example
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: thorntail-health-check
          group: io.thorntail.example
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: thorntail-health-check:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: thorntail
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - thorntail
        from:
          kind: ImageStreamTag
          name: thorntail-health-check:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: thorntail-health-check
      group: io.thorntail.example
    name: thorntail-health-check
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: thorntail-health-check
